### ISSUE TITLE
Explore option to not have text boxes appear for every single item

### ISSUE THREAD

**Issue by Dragion147** [cjmang/Archipelago#23]
### What feature would you like to see?

An example from Pokemon Emerald which provides options to pick if you want to see everything, only important or no messages at all. For Golden Sun this might be trickier as we have inventory limits to work with but items like gold do not occupy inventory space so do we really need it then? Perhaps it can also be made smarter that only messages are shown for important items or if you have close to full inventory. Earthbound also has a limited inventory system and they don't show anything specific unless its important or the inventory is full as well as another means of inspiration maybe?

```  
receive_item_messages:
    # Determines whether you receive an in-game notification when receiving an item. Items can still only be received in the overworld.
    # 
    # - All: Every item shows a message
    # - Progression: Only progression items show a message
    # - None: All items are added to your bag silently (badges will still show).
    all: 0
    progression: 1
    none: 0
```
